apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: tbd
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/dev/srvspetakkel
  env:
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spetakkel-v1
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: DATABASE_HOST
    value: b27dbvl009.preprod.local
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: spetakkel
  - name: VAULT_MOUNTPATH
    value: postgresql/preprod-fss/

