DELETE
FROM vedtaksperiode_tilstand
WHERE tilstand IN (
   'AVVENTER_SØKNAD_UFERDIG_FORLENGELSE',
   'AVVENTER_SØKNAD_FERDIG_FORLENGELSE',
   'AVVENTER_SØKNAD_FERDIG_GAP',
   'AVVENTER_SØKNAD_UFERDIG_GAP',
   'MOTTATT_SYKMELDING_FERDIG_FORLENGELSE',
   'MOTTATT_SYKMELDING_UFERDIG_FORLENGELSE',
   'MOTTATT_SYKMELDING_FERDIG_GAP',
   'MOTTATT_SYKMELDING_UFERDIG_GAP'
);

UPDATE vedtaksperiode_tilstand
SET tilstand='AVVENTER_INNTEKTSMELDING_ELLER_HISTORIKK'
WHERE tilstand IN (
   'AVVENTER_INNTEKTSMELDING_ELLER_HISTORIKK_FERDIG_GAP',
   'AVVENTER_INNTEKTSMELDING_UFERDIG_GAP',
   'AVVENTER_INNTEKTSMELDING_FERDIG_FORLENGELSE',
   'AVVENTER_INNTEKTSMELDING_UFERDIG_FORLENGELSE'
);

UPDATE vedtaksperiode_tilstand
SET tilstand='AVVENTER_BLOKKERENDE_PERIODE'
WHERE tilstand IN (
   'AVVENTER_UFERDIG',
   'AVVENTER_ARBEIDSGIVERE'
);

