name: main

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21.x'
        cache: 'gradle'
    - name: test and build
      run: ./gradlew build
      env:
        ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
    - name: build docker image
      uses: nais/docker-build-push@v0
      id: docker-build-push
      with:
        team: tbd
    - name: deploy to dev
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: dev-gcp
        RESOURCE: deploy/dev.yml
        IMAGE: ${{ steps.docker-build-push.outputs.image }}
    - name: deploy to prod
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: prod-gcp
        RESOURCE: deploy/prod.yml
        IMAGE: ${{ steps.docker-build-push.outputs.image }}

