name: master

on:
  push:
    branches:
    - master

env:
  APP: spetakkel
  TEAM: tbd
  IMAGE: ghcr.io/${{ github.repository }}/spetakkel

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17.x'
        cache: 'gradle'
    - name: create docker tag
      run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    - name: test and build
      run: ./gradlew test build
    - name: build docker image
      run: docker build . --pull -t ${{ env.IMAGE }}:${{ env.TAG }}
    - name: push docker image
      run: |
        echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin ghcr.io
        docker push ${{ env.IMAGE }}:${{ env.TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: deploy to dev
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        RESOURCE: deploy/dev.yml
        WAIT: false
        VAR: "image=${{env.IMAGE}},tag=${{env.TAG}},team=${{env.TEAM}},app=${{env.APP}}"
    - name: deploy to prod
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: prod-gcp
        RESOURCE: deploy/prod.yml
        WAIT: false
        VAR: "image=${{env.IMAGE}},tag=${{env.TAG}},team=${{env.TEAM}},app=${{env.APP}}"

